### ISSUE TITLE
bash completion doesn't work with recent versions of git.

### ISSUE THREAD

**Issue by dseomn** [TheLocehiliosan/yadm#321] opened 2021-02-03 03:01 UTC
It looks like https://github.com/TheLocehiliosan/yadm/blob/a5b1067e02abc10c183c3411ee8b40c53e306722/completion/bash/yadm#L6-L7 checks for a `_git` function, but https://github.com/git/git/commit/441ecdab37fefdacf32575a60aa523b2367c46f7  removed that function from git's bash completion. I'm *guessing* that the replacement is either `__git_main` or `__git_wrap__git_main`, but I'm not sure.

**Comment by TheLocehiliosan** [comment] 2021-02-07 22:14
This is a duplicate of #318, follow that issue for resolution.

**Closed by TheLocehiliosan** 2021-02-07 22:14 UTC
Labels: bug
