### ISSUE TITLE
zsh completions broken in yadm 3.0.0

### ISSUE THREAD

**Issue by sidmadala** [TheLocehiliosan/yadm#292] opened 2021-01-04 15:12 UTC
### Describe the bug

Yadm 2 completions worked very well, but when upgrading to version 3.0.0 through Homebrew, pressing `tab` yields the following error on the first try followed by silence on any other attempts in the shell. The completions file `_yadm` still exists in the proper `/usr/local/share/zsh/site-functions` directory.

<img width="541" alt="Screen Shot 2021-01-03 at 9 19 31 AM" src="https://user-images.githubusercontent.com/22417141/103548255-8127b200-4e73-11eb-9f96-15bf4bee369e.png">

### To reproduce

Can this be reproduced with the yadm/testbed docker image: Most likely no since I use MacOS and Homebrew

1. Type command `yadm`
2. Press `TAB`
3. See error

### Expected behavior

I'd expect the completions to show up with a description of each command.

### Environment

 - Operating system: [Ubuntu 18.04, yadm/testbed, etc.]
 - Version yadm: `yadm 3.0.0`
 - Version Git: `git version 2.30.0`

**Comment by erijo** [comment] 2021-01-04 17:22
What version of zsh are you using?

**Comment by sidmadala** [comment] 2021-01-04 18:31
zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by erijo** [comment] 2021-01-04 18:32
Can you try this to verify that it isn't something in your setup:
```sh
zsh -f
fpath=(/usr/local/share/zsh/site-functions $fpath)
autoload compinit
compinit
```
and then try to complete yadm commands again?

**Comment by sidmadala** [comment] 2021-01-04 18:43
I do not get the error, but I also do not get any suggestions either. Only folder names appear for autocompletion.

**Comment by erijo** [comment] 2021-01-04 19:51
Then the fpath is probably wrong. Does the path added contain the file `_yadm`?

**Comment by sidmadala** [comment] 2021-01-04 19:53
The first item in my `fpath` is `/usr/local/share/zsh/site-functions` which contains the `_yadm` file.

<img width="1434" alt="Screen Shot 2021-01-04 at 2 53 01 PM" src="https://user-images.githubusercontent.com/22417141/103573626-8baa7180-4e9c-11eb-87af-6467fe686fbd.png">

**Comment by TheLocehiliosan** [comment] 2021-01-04 20:14
I'm not a zsh user, and I just attempted to use the completions installed via HomeBrew. I put this in my .zshrc as suggested by HomeBrew:
```
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
  autoload -Uz compinit
  compinit -i
fi
```

And then started a zsh, and typed "yadm <TAB>", and I'm met with this error:
```
yadm _git:12: command not found: __yadm_main
```
and then afterwards, only get directory completions...

I'm not sure where that comes from yet, but I would guess it comes from the inherited git completions. I see this in /usr/local/share/zsh/site-functions/_git:

```
_git ()
{
	local _ret=1
	local cur cword prev

	cur=${words[CURRENT]}
	prev=${words[CURRENT-1]}
	let cword=CURRENT-1

	if (( $+functions[__${service}_zsh_main] )); then
		__${service}_zsh_main
	else
		emulate ksh -c __${service}_main
	fi

	let _ret && _default && _ret=0
	return _ret
}
```
But I'm not sure where `${service}` gets defined.

**Comment by erijo** [comment] 2021-01-04 20:27
It seems like the git completion shipped with git differs from the git completion shipped with zsh. The new yadm completion requires the latter.

If you try removing the `_git` symlink from the /usr/local/share/zsh/site-functions dir, does it work then (after starting a new shell)?

**Comment by sidmadala** [comment] 2021-01-04 20:44
It works if i rename/remove the _git symlink.

**Comment by TheLocehiliosan** [comment] 2021-01-04 20:47
I'm away at the moment, but later I'll dig into where the _git completions in home brew are coming from. I think there may still need to be some mitigation for this situation.

**Comment by erijo** [comment] 2021-01-04 20:52
Yes, I think we should keep this issue open until a proper fix is in place.

The git completions comes from the git package according to the image above (seen in symlink).

**Comment by TheLocehiliosan** [comment] 2021-01-04 20:54
Again, I'm away, but in my setup, there was also a second git completion. I'll look into it later for sure.

**Comment by sidmadala** [comment] 2021-01-04 20:55
My other git completions come from a zsh plugin called `zsh-useres/zsh-completions` which packages most of the default tools' completions into one folder. Yadm works fine when this other completion source is the one being used instead of the default `_git`.

**Comment by erijo** [comment] 2021-01-04 21:07
I've been able to reproduce this issue. I'll have a look and see if I can come up with a solution.

**Comment by erijo** [comment] 2021-01-04 23:29
I've just posted a PR that works for me in my testing. But more testing is of course welcome.

**Comment by TheLocehiliosan** [comment] 2021-01-05 02:08
@sidmadala I have tested @erijo's changes, and they work for me. It would be great to get further confirmation. Is it possible to copy the `completions/zsh/_yadm` file from the develop branch into /usr/local/share/zsh/site-functions, and then run `brew reinstall git`, and see if completions are working?

The brew reinstall should put the Git completions back into place if they were removed.

**Comment by sidmadala** [comment] 2021-01-05 02:15
Works for me. Don't know why the spacing is uneven though.

Git:
<img width="740" alt="Screen Shot 2021-01-04 at 9 14 47 PM" src="https://user-images.githubusercontent.com/22417141/103598937-e14d4100-4ed1-11eb-88fb-8c0f06ad23f5.png">

Yadm:
<img width="738" alt="Screen Shot 2021-01-04 at 9 13 50 PM" src="https://user-images.githubusercontent.com/22417141/103598905-caa6ea00-4ed1-11eb-8cba-fc2dd30126c7.png">

**Comment by xenoterracide** [comment] 2021-01-05 16:32
gI didn't get an error, but completions were stalling out zsh, and I had to kill them so I unloaded them.
```
1 ❯ zsh --version                                                                                       # ~
zsh 5.8 (x86_64-pc-linux-gnu)
❯ uname -a                                                                                              # ~
Linux freyja 5.10.2-2-MANJARO #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020 x86_64 GNU/Linux
```

**Comment by erijo** [comment] 2021-01-05 16:40
@xenoterracide: is this also with the fixed completions on the develop branch?

**Comment by erijo** [comment] 2021-01-05 22:22
@sidmadala: the mixed spacing was a consequent of how the completion was done.

All: I've now done yet another retake on the completion (see my [zsh-completion](https://github.com/erijo/yadm/tree/zsh-completion) branch) where I've simplified the completion and stopped using internal functions from the git completion. I've only done some simple testing so far, but it seems to work well.

Please try it and see if it works for you as well.

**Comment by sidmadala** [comment] 2021-01-05 22:32
@erijo, looks good to me. Separating the `yadm` specific commands is a nice touch.

<img width="725" alt="Screen Shot 2021-01-05 at 5 30 47 PM" src="https://user-images.githubusercontent.com/22417141/103706950-c20aee00-4f7b-11eb-835e-681a2cc25cff.png">

**Comment by TheLocehiliosan** [comment] 2021-01-06 16:25
@erijo - Can you create a new PR for the updated zsh completions? (assuming the are working better)

**Comment by erijo** [comment] 2021-01-06 18:49
@TheLocehiliosan: yes, will do. I have a few minor things to fix first.

**Closed** 2021-01-07 16:04 UTC
Labels: bug

**Comment by xenoterracide** [comment] 2021-01-07 16:07
just an FYI I plan on testing this, just haven't gotten around to it yet. no later than this weekend though, maybe tonight. I should probably update the aur `PKGBUILD` to do it.
